/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ultralesson.capstoneProject.fruitbowl;

public class App {
    public static void main(String[] args) {
        Color red=new Color.Builder().setRed(255).createColor();
        Color green=new Color.Builder().setGreen(255).createColor();
        Taste sweet=new Taste.Builder("sweet").createTaste();
        Taste sour=new Taste.Builder("sour").createTaste();
        Fruit apple1=new Fruit.Builder("apple")
                .setColor(red)
                .setTaste(sweet)
                .createFruit();
        Fruit apple2=new Fruit.Builder("apple")
                .setColor(red)
                .setTaste(sweet)
                .createFruit();
        Fruit grapes=new Fruit.Builder("grapes")
                .setColor(green)
                .setTaste(sour)
                .createFruit();
        Fruit orange=new Fruit.Builder("orange")
                .setColor(red)
                .setTaste(sour)
                .createFruit();
        Fruit mango=new Fruit.Builder("mango")
                .setColor(green)
                .setTaste(sour)
                .createFruit();

        Bowl bowl=new Bowl();
        bowl.addFruits(apple1);
        bowl.addFruits(apple2);
        bowl.addFruits(grapes);
        bowl.addFruits(orange);
        bowl.addFruits(mango);

        Basket basket=new Basket(3);
        System.out.println(basket.getLayers());
        FruitsSegregator fruitsSegregator=new FruitsSegregator();
        fruitsSegregator.segregateByName(bowl,basket);
        for(Bowl bowl1: basket.getLayers()){
            System.out.println(bowl1.getFruits());
        }
    }
}
