/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ultralesson.fruitbowl;

import com.ultralesson.capstoneProject.fruitbowl.App;
import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {
    
}
